@startuml

title __SPECIALREQUESTS's Class Diagram__\n

  namespace  {
    namespace om.example.demo {
      namespace request {
        namespace specialRequests {
          class com.example.demo.request.specialRequests.AssignPowerUnitToStation {
              ~ idPowerUnit : Long
              ~ idStation : Long
              + AssignPowerUnitToStation()
              + AssignPowerUnitToStation()
              + getIdPowerUnit()
              + getIdStation()
              + setIdPowerUnit()
              + setIdStation()
          }
        }
      }
    }
  }
  

  namespace  {
    namespace om.example.demo {
      namespace request {
        namespace specialRequests {
          class com.example.demo.request.specialRequests.Car2Request {
              - idCar : Long
              - idUser : Long
              + Car2Request()
              + Car2Request()
              + getIdCar()
              + getIdUser()
              + setIdCar()
              + setIdUser()
          }
        }
      }
    }
  }
  

  namespace  {
    namespace om.example.demo {
      namespace request {
        namespace specialRequests {
          class com.example.demo.request.specialRequests.CheckInRequest {
              - idCar : Long
              - idPowerUnit : Long
              - idUser : Long
              + CheckInRequest()
              + getIdCar()
              + getIdPowerUnit()
              + getIdUser()
              + setIdCar()
              + setIdPowerUnit()
              + setIdUser()
          }
        }
      }
    }
  }
  

  namespace  {
    namespace om.example.demo {
      namespace request {
        namespace specialRequests {
          class com.example.demo.request.specialRequests.CheckOutRequest {
              - idCar : Long
              - idPowerUnit : Long
              - idUser : Long
              + CheckOutRequest()
              + getIdCar()
              + getIdPowerUnit()
              + getIdUser()
              + setIdCar()
              + setIdPowerUnit()
              + setIdUser()
          }
        }
      }
    }
  }
  

  namespace  {
    namespace om.example.demo {
      namespace request {
        namespace specialRequests {
          class com.example.demo.request.specialRequests.CityRequest {
              - city : String
              + CityRequest()
              + CityRequest()
              + getCity()
              + setCity()
          }
        }
      }
    }
  }
  

  namespace  {
    namespace om.example.demo {
      namespace request {
        namespace specialRequests {
          class com.example.demo.request.specialRequests.GoingToQueueRequest {
              - fastCharge : boolean
              - givenPercentageForCharging : int
              - id : Long
              - idCar : Long
              - idPowerUnit : Long
              - idUser : Long
              + GoingToQueueRequest()
              + GoingToQueueRequest()
              + getGivenPercentageForCharging()
              + getId()
              + getIdCar()
              + getIdPowerUnit()
              + getIdUser()
              + isFastCharge()
              + setFastCharge()
              + setGivenPercentageForCharging()
              + setId()
              + setIdCar()
              + setIdPowerUnit()
              + setIdUser()
          }
        }
      }
    }
  }
  

  namespace  {
    namespace om.example.demo {
      namespace request {
        namespace specialRequests {
          class com.example.demo.request.specialRequests.RequestWith2IDs {
              - idStation : Long
              - idUser : Long
              + RequestWith2IDs()
              + RequestWith2IDs()
              + getIdStation()
              + getIdUser()
              + setIdStation()
              + setIdUser()
          }
        }
      }
    }
  }
  

  namespace  {
    namespace om.example.demo {
      namespace request {
        namespace specialRequests {
          class com.example.demo.request.specialRequests.RequestWithIdOnly {
              ~ id : Long
              + RequestWithIdOnly()
              + RequestWithIdOnly()
              + getId()
              + setId()
          }
        }
      }
    }
  }
  

  namespace  {
    namespace om.example.demo {
      namespace request {
        namespace specialRequests {
          class com.example.demo.request.specialRequests.UpdateToQueue {
              - amount : float
              - endTime : String
              - fastCharge : boolean
              - id : Long
              - idPowerUnitEntity : Long
              - idUserEntity : Long
              - startTime : String
              + UpdateToQueue()
              + UpdateToQueue()
              + getAmount()
              + getEndTime()
              + getId()
              + getIdPowerUnitEntity()
              + getIdUserEntity()
              + getStartTime()
              + isFastCharge()
              + setAmount()
              + setEndTime()
              + setFastCharge()
              + setId()
              + setIdPowerUnitEntity()
              + setIdUserEntity()
              + setStartTime()
          }
        }
      }
    }
  }
  

  com.example.demo.request.specialRequests.RequestWithIdOnly .up.|> java.io.Serializable


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
